### ISSUE TITLE
Why not define backpipe by referencing forward-pipe?

### ISSUE THREAD

**Issue by peterhurford** [robertzk/backpipe#1]
```R
`%<%` <- function(lhs, rhs) rhs %>% lhs
```

...Seems much simpler and more DRY, no?

**Comment by robertzk** [comment]
Doesn't work :(

On Tue, Feb 17, 2015 at 12:38 AM, Peter Hurford <notifications@github.com>
wrote:

> `%<%` <- function(lhs, rhs) rhs %>% lhs
>
> ...Seems much simpler, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/backpipe/issues/1>.
>



-- 
-Robert Krzyzanowski

**Comment by robertzk** [comment]
This was my very first attempt, but due to weird lazy evaluation shenanigans it fails.

```r
> force() %<% function(x) x
Error in force() : argument "x" is missing, with no default
```

Another failed attempt is the more clever

```r
> `%<%` <- function(lhs, rhs) { call <- sys.call(); call[[1]] <- quote(magrittr::`%>%`);
    call[c(2,3)] <- call[c(3,2)]; eval.parent(call) }
> force() %<% function(x) x
Error in pipes[[i]] : subscript out of bounds
```
